[2024-12-10T17:38:21.288+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-10T17:38:21.307+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.predict scheduled__2024-12-09T15:00:00+00:00 [queued]>
[2024-12-10T17:38:21.316+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.predict scheduled__2024-12-09T15:00:00+00:00 [queued]>
[2024-12-10T17:38:21.317+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-10T17:38:21.331+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): predict> on 2024-12-09 15:00:00+00:00
[2024-12-10T17:38:21.339+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=469) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-10T17:38:21.340+0000] {standard_task_runner.py:72} INFO - Started process 482 to run task
[2024-12-10T17:38:21.340+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'predict', 'scheduled__2024-12-09T15:00:00+00:00', '--job-id', '1901', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpwo94louh']
[2024-12-10T17:38:21.341+0000] {standard_task_runner.py:105} INFO - Job 1901: Subtask predict
[2024-12-10T17:38:21.385+0000] {task_command.py:467} INFO - Running <TaskInstance: car_price_prediction.predict scheduled__2024-12-09T15:00:00+00:00 [running]> on host 4b38f6471eac
[2024-12-10T17:38:21.456+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-09T15:00:00+00:00'
[2024-12-10T17:38:21.457+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-10T17:38:21.458+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-10T17:38:21.458+0000] {logging_mixin.py:190} INFO - Current task name:predict state:running start_date:2024-12-10 17:38:21.308374+00:00
[2024-12-10T17:38:21.459+0000] {logging_mixin.py:190} INFO - Dag name:car_price_prediction and current dag run status:running
[2024-12-10T17:38:21.459+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-10T17:38:21.460+0000] {logging_mixin.py:190} INFO - Loading the model...
[2024-12-10T17:38:21.460+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/modules/predict.py", line 43, in predict
    model = load_model(model_path)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/modules/predict.py", line 8, in load_model
    with open(model_path, 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/models/cars_pipe_202412101252.pkl'
[2024-12-10T17:38:21.471+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-10T17:38:21.472+0000] {logging_mixin.py:190} INFO - Task start:2024-12-10 17:38:21.308374+00:00 end:2024-12-10 17:38:21.471534+00:00 duration:0.16316
[2024-12-10T17:38:21.472+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): predict> dag:<DAG: car_price_prediction> dagrun:<DagRun car_price_prediction @ 2024-12-09 15:00:00+00:00: scheduled__2024-12-09T15:00:00+00:00, state:running, queued_at: 2024-12-10 17:36:18.324725+00:00. externally triggered: False>
[2024-12-10T17:38:21.473+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'data/models/cars_pipe_202412101252.pkl'
[2024-12-10T17:38:21.474+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=car_price_prediction, task_id=predict, run_id=scheduled__2024-12-09T15:00:00+00:00, execution_date=20241209T150000, start_date=20241210T173821, end_date=20241210T173821
[2024-12-10T17:38:21.484+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-10T17:38:21.485+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1901 for task predict ([Errno 2] No such file or directory: 'data/models/cars_pipe_202412101252.pkl'; 482)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/modules/predict.py", line 43, in predict
    model = load_model(model_path)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/modules/predict.py", line 8, in load_model
    with open(model_path, 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/models/cars_pipe_202412101252.pkl'
[2024-12-10T17:38:21.515+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-10T17:38:21.530+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-10T17:38:21.532+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
